# Shubham Luharuka
# The Spark Foundation
# Task 6- Prediction using Decision Tree Algorithm

In [1]:
#load all important libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
import sklearn
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
#Load Data
data=pd.read_csv("Iris.csv",index_col=['Id'])

In [3]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id                                                                       
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data.nunique()

SepalLengthCm    35
SepalWidthCm     23
PetalLengthCm    43
PetalWidthCm     22
Species           3
dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


In [6]:
X=data[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
Y=data['Species']

In [12]:
# Split the dataset into train and test part
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.25, random_state=42)
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id                                                           
5              5.0           3.6            1.4           0.2
33             5.2           4.1            1.5           0.1
143            5.8           2.7            5.1           1.9
86             6.0           3.4            4.5           1.6
87             6.7           3.1            4.7           1.5
..             ...           ...            ...           ...
72             6.1           2.8            4.0           1.3
107            4.9           2.5            4.5           1.7
15             5.8           4.0            1.2           0.2
93             5.8           2.6            4.0           1.2
103            7.1           3.0            5.9           2.1

[112 rows x 4 columns]

In [8]:
y_train

Id
5          Iris-setosa
33         Iris-setosa
143     Iris-virginica
86     Iris-versicolor
87     Iris-versicolor
            ...       
72     Iris-versicolor
107     Iris-virginica
15         Iris-setosa
93     Iris-versicolor
103     Iris-virginica
Name: Species, Length: 112, dtype: object

In [13]:
#Train the Model
classifier=DecisionTreeClassifier(max_depth=3,criterion='gini',splitter='random',min_samples_split=10)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_split=10, splitter='random')

In [10]:
y_pred=classifier.predict(X_test)

In [15]:
#Prediction and Accuracy
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred))
print()
print ("Accuracy : ", accuracy_score(y_test,y_pred)*100)
print()
print("Report : ",classification_report(y_test, y_pred))

Confusion Matrix: 
[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]

Accuracy :  100.0

Report :                   precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      1.00      1.00        11
 Iris-virginica       1.00      1.00      1.00        12

       accuracy                           1.00        38
      macro avg       1.00      1.00      1.00        38
   weighted avg       1.00      1.00      1.00        38

